[build-system]
requires =["setuptools"]
build-backend = "setuptools.build_meta"


[tool.black]
target-version= ['py310']
line-length=89
include = '\.pyi?$'
exclude = '''
/(
	\.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''

[tool.isort]
profile='black'
multi_line_output=3
