name: Tests
on:
  pull_request:
    branches: [main]
  push:
jobs:
  test:
    # prevent this action from running on forks
    if: github.repository == 'dgaines2/vasp_manager'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -e '.[dev]'
      - uses: pre-commit/action@v3.0.1
      - name: Coverage
        run: |
          coverage run
          coverage report -m
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
